#!/bin/bash

#this script will eventually be used for doing grep/ack through huge haystacks of files
#for plaintext, including searching plaintext within ms word, pdf, and excel files

#searching:
#use ack not grep
#
#apropos:
#MS Word 			= catdoc -a -w
#PDF with text		= pdftotext -nopgbrk -raw -layout -q "<file>" - 
#PDF without text	= 
#Excel 				= xls2csv -q 0 -g 2 -f d/m/yyyy -b --------------------------------

#alias ransack='find . -exec grep --color=auto --binary-files=text -directories=recurse "$arg" {} +'

#find . | documentcat $1 | ack	 $2

# INITIALIZE #
##############
if [ $1 = "" ]; then
	HAYSTACK=$(pwd)
else
	HAYSTACK=$1
	if [ ! -d "$1" ]; then
		echo "Invalid or nonexistent path."
		HAYSTACK=""
	fi
fi

echo $HAYSTACK