#!/usr/bin/bash

set -x

#set variables
pg_dump="/home/Ryan/pgsql/bin/pg_dump.exe"
dump_path="C:/Dropbox/Sierra/backup/"
current_date=$(date +%Y-%m-%d__%H-%M-%S)

fatal="0"
echo "$fatal"

if [[ ! -d "$dump_path" ]]; then
	echo "Dump path not found:""$dump_path";
	fatal=1
fi

if [[ ! -f "$pg_dump" ]]; then
	echo "pg_dump not found:""$pg_dump";
	fatal=1
fi

echo "Fatality: ""$fatal"
if [[ "$fatal" ]]; then
	echo "FATAL: Critical files not found.";
	exit 1
fi

echo "Success."
exit 0

backup_file=$dump_path$current_date".backup"
log_file=$dump_path$current_date".log"

#create the backup
source ~/bin/cygwin/susie_dump $backup_file $log_file

stat $backup_file

until [[ "$INPUT" == "y" ]]; do
        echo "Continue? (y/n)"
        read INPUT

        case $INPUT in
               y)
                        ;;     #nothing
               n)
               exit 1          #exit with error
                        ;;
               *)
        esac
done

#drop the sandbox
source ~/bin/cygwin/susie_drop

#create the sandbox
source ~/bin/cygwin/susie_create

#restore to sandbox
source ~/bin/cygwin/susie_restore
