#!/usr/bin/env bash
#
#saves hash values of a directory and all the files in it
#submits the hash values to team cymru for analysis and saves the output
#
# http://reverseengineering.stackexchange.com/questions/206/where-can-i-as-an-individual-get-malware-samples-to-analyze

#If no argument was passed, assume we are working in the present working directory
#if [[ ! $1 ]]

#initialize the hash list
echo "begin" >> $1_list.md5

#save md5 values individually
find $1 -type f -not -name "*.md5" | while read file;
do
        md5deep $file | tee $file.md5 >> $1_list.md5
done

#close the hash list
echo "end" >> $1_list.md5

#netcat the output to cymru.org and save the output to file
ncat hash.cymru.com 43 < $1_list.md5 > $1_list_analyzed.md5

less $1_list_analyzed.md5
