#!/usr/bin/env python3
#
"""Print some random piece of advice."""
import json
import urllib.request

__ADVICE_API__ = "https://api.adviceslip.com/advice"


def main():
    with urllib.request.urlopen(__ADVICE_API__) as r:
        r_json = json.loads(r.read().decode())

    print(r_json.get("slip", {}).get("advice"))


if __name__ == "__main__":
    main()

# EOF
