#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# I have no idea if this works

main() {
  # download album art from amazon
  local y="$*"
  awk '/View larger image/{gsub(/^.*largeImagePopup\(.|., .*$/,"");print;exit}' <(curl -s 'http://www.albumart.org/index.php?srchkey='"${y// /+}"'&itempage=1&newsearch=1&searchindex=Music')
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
