#!/usr/bin/env sh
#
# alignc -- center text in a terminal
# Copyright (C) 2010-2012  Alan SCHNEIDER
#                          <shk.schneider[at]gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY.
# This is free software, and you are welcome to redistribute it
# under certain conditions.
#

[ $# -eq 0 ] && echo "Usage: alignc <text [...]>" >&2 && exit 1

columns=$(echo "$(tput cols)/2" | bc -q)
for argv in "$@" ; do
    offset=$(echo "${#argv}/2" | bc -q)
    # we will actually want to fix this SC2004 but I cba right now
    # shellcheck disable=SC2004
    cols=$(($columns + $offset + 1))
    printf "%${cols}s\\n" "$argv"
done

# EOF
