#!/usr/bin/env bash
#

for file in "$@"; do
  date="$(date +%Y%m%d-%H%m%S)" || exit
  if command -v greadlink &> /dev/null; then
    oldname="$(greadlink -f "$file")" || exit
  else
    oldname="$(readlink -f "$file")" || exit
  fi
  newname="$oldname".bak."$date"
  cp "$file" "$newname"
done

# EOF
