#!/usr/bin/env bash
# GNU bash, version 4.3.18(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Applies some night time styles and plays a tone to tell me to go to bed.
# Invoking this with cron

# Functions {{{1
verbose() {
  if [[ "$verbose" -ge "1" ]] && [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}

error() {
  if [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}
# 1}}}
tmux_nightstyle="/home/ryan/.config/tmux/color-slate.conf"
bedtime_tone="/media/vault/public/audio/effects/pdsounds/Zymbel_The_Real_Horst-1113884951.mp3"

broadcast Lights out
if [[ -f "$tmux_nightstyle" ]]; then
  tmux source-file "$tmux_nightstyle" 1> /dev/null
else
  error "tmux night style not found."
fi

if [[ -f "$bedtime_tone" ]]; then
  play -q "$bedtime_tone" &
else
  error "Bedtime tone not found."
fi

# vim: ft=sh foldmethod=marker:

