#!/usr/bin/env bash
#
# run a game with my favorite sugar

set -o nounset     # expanding unset variables is fatal
shopt -s nullglob  # globs that match nothing expand to ""

log() {
  local msg=${1:-}
  local level="${2:-INFO}"
  now=$(date "+%Y-%m-%d %H:%M:%S%z")
  echo "$now $HOSTNAME $(basename "$0"):$level $msg" 1>&2
}

# Dependencies {{{1
dependencies="gamescope rich"
missing_dependencies=""

is_missing=0
for dependency in $dependencies; do
  if ! command -v "$dependency" > /dev/null 2>&1; then
    # If not found, add to missing_dependencies string
    missing_dependencies="$missing_dependencies $dependency"
    is_missing=1
  fi
done

if [ $is_missing -eq 1 ]; then
  printf "Required dependencies are missing:%s\\n" "$missing_dependencies"
  exit 1
fi

unset dependencies missing_dependencies is_missing

if [[ -n "${MANGOHUD_CONFIGFILE:-}" ]]; then
  if [[ ! -r "$MANGOHUD_CONFIGFILE" ]]; then
    log "Mangohud config not found: \`$MANGOHUD_CONFIGFILE\`" 1>&2
  fi
fi
# Dependencies 1}}}

main() {
#   --expose-wayland # DONT DO THIS until you know mangoapp supports wayland
#   we must `env LD_PRELOAD=""` to prevent stuttering after 20 minutes

  # shellcheck disable=SC2068
  ( set -x ;
    env LD_PRELOAD="" \
      gamescope \
        --fullscreen \
        --mangoapp \
        --nested-height 1080 \
        --nested-width 1920 \
        --output-height 1080 \
        --output-width 1920 \
      $@ 2>&1
  ) | \
    grep -Fv \
    -e "got the same buffer committed twice, ignoring." \
    -e "Could not resolve keysym" \
    -e "Loading scripts from:" \
    -e "Running script file" \
    -e "LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32)" \
    | \
    uniq
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  rich --rule
  log "Launching command: $*"
  main "$@"
  rich --rule
fi

# EOF
