#!/usr/bin/env python3
#
"""Print a random cat fact."""
import json
import urllib.request

__CAT_FACT_API__ = 'https://meowfacts.herokuapp.com/'


def main():
    with urllib.request.urlopen(__CAT_FACT_API__) as r:
        r_json = json.loads(r.read().decode())

    print("\n".join(r_json.get("data")))


if __name__ == "__main__":
    main()

# EOF
