#!/usr/bin/env bash
#
#   Try to open a video file, and then ask me if I want to delete it.
#

if ! command -v confirm >/dev/null 2>&1 ; then echo "Missing dependency: confirm" 1>&2 ; exit 1 ; fi

if [[ -r "$1" ]]; then
  mpv "$1"
else
  echo "$1 is not a readable file." 1>&2
  exit 1
fi

if confirm "Delete the file? $1 " ; then
  rm "$1"
fi

# EOF
