#!/usr/bin/env bash
# GNU bash, version 4.3.42(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2016 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
#   Try to open a file, and then ask me if I want to delete it.

if [[ -r "$1" ]]; then
  mpv "$1"
else
  echo "$1 is not a readable file." 1>&2
  exit 1
fi

confirm "Delete the file? $1 " && >"$1" || exit 0

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
