#!/usr/bin/env sh
#
# ask the user to confirm if they want to continue
# arguments passed will be the query question
#

[ -n "$*" ] && QUERY="$*"" (y/n)" || QUERY="Continue? (y/n)"

until [ "$INPUT" = "y" ]; do
  echo "$QUERY"
  read -r INPUT

  case $INPUT in
          y)
          exit "0"
          ;;
          n)
          exit "1"
          ;;
          *)
          ;;
  esac
done
