#!/usr/bin/env sh
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  for file in "$@"; do
    if ! python -c "import csv,json,fileinput; print(json.dumps(list(csv.reader(fileinput.input()))))" "$file" 1> "${file%%csv}json" ; then
      exit_code="$?"
    fi
  done

  return "${exit_code:-0}"
}

main "$@"
exit $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
