#!/usr/bin/env python3
#
"""Get a dictionary definition for a word."""
import requests
import sys


DICTIONARY_URI = "dict://dict.org/d:hello"


def _define(word: str) -> str:
    r = requests.get(DICTIONARY_URI)
    return word


def main() -> int:
    if words := sys.argv[1:]:
        for word in words:
            print(_define(word))
    else:
        print("Give me a word to define", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise NotImplementedError("This doesn't work yet. Use xonsh command or migrate that code here.")
    sys.exit(main())

# EOF
