#!/usr/bin/env bash
# GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin17.7.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#

# Usage {{{1
usage() {
cat <<EOD
Usage: $(basename "$0") [OPTION]

diffs all the files in two directories against each other using vimdiff

Options
  -?, --help                  print this help and exit
  -1                          first directory
  -2                          second directory
EOD
exit 1
}
# Usage 1}}}
# Parameters {{{1
#
while :
do
  case ${1:-} in
    --help | -\?)
      usage
      exit 0
      ;;
    -1)
      dir1=$2
      shift 2
      ;;
    -2)
      dir2=$2
      shift 2
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      verbose=$((verbose+1))
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
# Parameters 1}}}

if ! command -v vimdiff >/dev/null 2>&1 ; then echo "Missing dependency: vimdiff" 1>&2 ; exit 1 ; fi

if [[ -z "$dir1" ]] ; then
  echo "Argument not optional: -1"
  fatal=1
elif [[ ! -d "$dir1" ]] ; then
  echo "Not a directory: $dir1"
  fatal=1
fi

if [[ -z "$dir2" ]] ; then
  echo "Argument not optional: -2"
  fatal=1
elif [[ ! -d "$dir2" ]] ; then
  echo "Not a directory: $dir2"
  fatal=1
fi
[[ $fatal -gt 0 ]] && exit 1


main() {
  declare -a dir1_files
  declare -a dir2_files

  # verify files are the same
  for file in "${dir1}"/*; do
    dir1_files+=("$(basename "$file")")
  done
  for file in "${dir2}"/*; do
    dir2_files+=("$(basename "$file")")
  done

  if [[ "${dir1_files[*]}" != "${dir2_files[*]}" ]] ; then
    echo "Files don't match:"
    diff <(printf '%s\n' "${dir1_files[@]}") <(printf '%s\n' "${dir2_files[@]}")
    exit 1
  fi

  for file in ${dir1_files[*]} ; do
    if [[ -s "${dir1}/$file" ]] && [[ -s "${dir2}/$file" ]] ; then
      diff -q "${dir1}/$file" "${dir2}/$file" || vimdiff "${dir1}/$file" "${dir2}/$file"
    fi
  done
}

main "$@"

# EOF
