#!/usr/bin/env bash
# GNU bash, version 4.3.11(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Functions {{{1
verbose() {
  if [[ "$verbose" = "1" ]]; then
    echo "$1" >&2
  fi
}

error() {
  echo "$1" >&2
}

dirfiles() {
  cd "$1" && find -path "*.git" -prune -o -print | sort
}
# }}}
# Usage {{{1
#
usage() {
cat <<EOD
dirdiff
© Copyright 2014 Ryan Delaney. All rights reserved.
Web site: http://github.com/rpdelaney

dirdiff prints the difference between two directories

Usage: dirdiff [OPTION] [PATH] [PATH]

Options
  -?, --help                  print this help and exit
  -v, --verbose               increase verbosity
EOD
exit 1
}
# }}}
# Parameters {{{1
#
while :
do
  case $1 in
    --help | -\?)
      usage
      exit 0
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      local verbose=$((verbose+1))
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
path1="$1"
path2="$2"
# }}}
# Work {{{1
vimdiff <(dirfiles "$path1") <(dirfiles "$path2");
# }}}

# vim: ft=sh foldmethod=marker:
