#!/usr/bin/env bash
#
DISPLAY_SECONDARY=eDP-1-1
DISPLAY_PRIMARY=HDMI-0

if xrandr | grep "$DISPLAY_PRIMARY disconnected"; then
    xrandr --output "$DISPLAY_PRIMARY" --off --output "$DISPLAY_SECONDARY" --auto
else
    xrandr --output "$DISPLAY_SECONDARY" --auto --output "$DISPLAY_PRIMARY" --auto --left-of "$DISPLAY_SECONDARY"
fi

# EOF
