#!/usr/bin/env sh
#

if [ -n "$DISCLAIMER" ] ; then
  printf "%s" "$DISCLAIMER" && exit 0
  exit 1
fi

[ -z "${DISCLAIMER-unset}" ] && exit 0

cat <<EOD
This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the README file for additional terms and conditions on your use of this
software.
EOD

# EOF
