#!/usr/bin/env sh
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

if [ -n "$DISCLAIMER" ] ; then
  printf "%s" "$DISCLAIMER" && exit 0
  exit 1
fi

[ -z "${DISCLAIMER-unset}" ] && exit 0

cat <<EOD
This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the README file for additional terms and conditions on your use of this
software.
EOD

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
