#!/usr/bin/env bash
#
# try to figure out which operating system and distribution we're on, and print it
#

if ! command -v ostype > /dev/null 2>&1 ; then echo "Missing dependency: ostype" 1>&2 ; exit 1 ; fi

_macos_version() {
  if ! command -v system_profiler >/dev/null 2>&1 ; then echo "Missing dependency: system_profiler" 1>&2 ; return 1 ; fi
  if ! command -v awk >/dev/null 2>&1 ; then echo "Missing dependency: awk" 1>&2 ; return 1 ; fi

  system_profiler SPSoftwareDataType | grep 'System Version' | awk '{print $3 "-" $4}'
}

main() {
  local ostype
  ostype="$(ostype)"

  if [[ "$ostype" == "macos" ]]; then
    _macos_version
  elif [[ "$ostype" == "linux" ]]; then
    [[ "$PREFIX" =~ "termux" ]] && echo "termux" && return
    [[ -f /etc/redhat-release ]] && echo "redhat" && return
    [[ -f /etc/fedora-release ]] && echo "fedora" && return
    [[ -f /etc/SuSE-release ]] && echo "suse" && return
    [[ -f /etc/debian_version ]] && echo "debian" && return
    [[ -f /etc/arch-release ]] && echo "arch" && return
    [[ -f /etc/gentoo-release ]] && echo "gentoo" && return
    [[ -f /etc/slackware-version ]] && echo "slackware" && return
    [[ -f /etc/frugalware-release ]] && echo "frugalware" && return
    [[ -f /etc/altlinux-release ]] && echo "altlinux" && return
    [[ -f /etc/mandriva-release ]] && echo "mandriva" && return
    [[ -f /etc/meego-release ]] && echo "meego" && return
    [[ -f /etc/angstrom-version ]] && echo "angstrom" && return
    [[ -f /etc/mageia-release ]] && echo "mageia" && return

    # https://www.freedesktop.org/software/systemd/man/os-release.html
    if [[ -r /etc/os-release ]]; then
      id="$(grep 'ID=' /etc/os-release | cut -d'=' -f 2)"
      [[ -n "$id" ]] && echo "$id" && return 0
    fi
  else
    return 1
  fi
}

main "$@"

# EOF
