#!/usr/bin/env bash
#
# Shows disk usage of folders at pwd
#

# Usage {{{1
#
usage() {
cat <<EOD
duhere is a wrapper for du that shows human-readable disk usage of files in the
current working directory.

Usage: duhere [OPTION]

Options
  -?, --help                  print this help and exit
  -v, --verbose               increase verbosity
EOD
exit 1
}
# }}}

if [[ "$(df -T "$PWD" | tail -n1 | awk '{print $2}')" == "btrfs" ]] ; then
  btrfs filesystem df .
else
  du -h -d 1 | sort -h -r
fi

# EOF
