#!/usr/bin/env bash
#
# decompress archives based on mimetype
#
# TODO: confirm that all commands extract to a directory named after
#       the archive
#

  # Validate that we are working with a file
if [[ ! -f "$1" ]] ; then
    echo "extract:: FATAL no such file $1"
    exit 1
fi

  # get the filename
filename="$(basename $1)"   # Full filename
extension="${filename##*.}" # Outer (last) extension only
shortname="${filename%.*}"  # Filename without the outer extension
  # get the mime type
    # this should use xdg-mime query filetype "$1" instead
mime=$(file -Lb --mime-type "$1")
echo "mimetype is: $mime"
case "${mime#*-}" in
    tar)
        # TODO: Move this to a second step (for one-pass tar extraction) --R. Delaney 2014-01-29T09:35-0800 OpenGPG: 0D98863B4E1D07B6
        dep="tar"
        cmd=(tar kxfv "$1")
        ;;
    bzip2)
    dep="bunzip2"
        cmd=(bunzip2 "$1")
        ;;
    tar.bz2)
        dep="tar"
        cmd=(tar kxjfv "$1")
        ;;
    tar.gz)
        dep="tar"
        cmd=(tar kxzfv "$1")
        ;;
    tbz2)
        dep="tar"
        cmd=(tar kxjfv "$1")
        ;;
    tgz)
        dep="tar"
        cmd=(tar kxzfv "$1")
        ;;
    xz)
        dep="xz"
        cmd=(xz -dk "$1")
        ;;
    rar)
        dep="unrar"
        cmd=(unrar x "$1")
        ;;
    gzip)
        dep="gzip"
        cmd=(gzip -d --keep "$1")
        ;;
    application/zip)
        # Extracts to directory OK
        dep="unzip"
        cmd=(unzip "$1")
        ;;
    Z)
        dep="gzip"
        cmd=(gzip -vd --keep "$1")
        ;;
    7z-compressed)
        dep="7za"
        cmd=(7za x "$1")
        ;;
    *)
    echo "extract: unrecognized mimetype $mime"
        exit 1
        ;;
esac

#Check for missing dependency
[[ "$dep" ]] && type -P "$dep" > /dev/null || { echo "extract:: Missing dependency for MIME type $mime: $dep"; exit 1; }

#Run the extraction command
"${cmd[@]}"

# Warn me if I deleted the file somehow
[[ -e "$1" ]] || echo "extract:: WARNING! $1 was removed after extracting."

