#!/usr/bin/bash
#
# bash function to decompress archives
#

if [ -f "$@" ] ; then
    
    file=$(basename "$@")
    ext="${file##*.}"
    lext="${ext,,}"
    
    #extension must not be zero-length
    [ -n "$ext" ] && echo "'"$@"' zero-length file extension" & exit 1 ;
    
    #since it's not, see if we can recognize it
    case "$lext" in
        bz2) 
            bunzip2 "$@"
            ;;
        tar.bz2)
            DEP="tar"
            CMD="tar xvjf ""$@"
            ;;
        tar.gz) 
            DEP="tar"
            CMD="tar xvzf ""$@"
            ;;
        tar) 
            DEP="tar"
            CMD="tar xvf ""$@"
            ;;
        rar) 
            DEP="unrar"
            unrar x "$@"
            ;;
        gz) 
            DEP="gunzip"
            CMD="gunzip ""$@"
            ;;
        tbz2) 
            DEP="tar"
            CMD="tar xvjf ""$@"
            ;;
        tgz) 
            DEP="tar"
            CMD="tar xvzf ""$@"
            ;;
        zip) 
            DEP="unzip"
            CMD="unzip ""$@"
            ;;
        Z)
            DEP="uncompress"
            CMD="uncompress ""$@"
            ;;
        7z) 
            DEP="7za"
            CMD="7za x ""$@"
            ;;
        *) 
            echo "'"$@"' unrecognized file extension"
            exit 1
            ;;
    esac 
    
    #Check for missing dependency
    [[ "$DEP" ]] && type -P "$DEP" > /dev/null || { echo "Missing dependency: ""$DEP"; exit 1; }
    
    #Run the extraction command
    bash -c "$CMD"
    
else
    echo "'"$@"' is not a valid file"
    exit 1
fi
