#!/usr/bin/env bash
#
# find a file by its name, excluding .git
# https://stackoverflow.com/questions/4210042/how-to-exclude-a-directory-in-find-command

set -u

if git rev-parse 2> /dev/null ; then
  git ls-files -- "**/${1}"
else
  find . -name ".git" -prune -o -iname "*${1}*" -print
fi

# EOF
