#!/usr/bin/env bash
# GNU bash, version 4.3.33(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2015 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Functions {{{1
error() {
  echo "$1" >&2 || return 1
}
# 1}}}
# Usage {{{1
#
usage() {
cat <<EOD
flog initializes a new bash script with vim modelines, shebang, and the like.

Usage: flog [OPTION] FILENAME

Options
  -?, --help                  print this help and exit
EOD
exit 1
}
# 1}}}
# Validation {{{1
if [[ -z "$1" ]]; then
  error "FATAL: Argument not optional. Try 'flog --help' for usage information."
fi
# 1}}}

boilerplate() {
  copyright="$(copyright || return 1)"
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s %s\n' '#' "$(bash --version | head -n1)"
  printf '%s\n' "# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:"
  printf '%s\n' '#'
  printf '# %s\n' "$copyright"
  sed 's@^@# @' < <(disclaimer) || return 1
  printf '\n\n'

cat <<EOD
main() {
  :
}

main "\$@"
exit \$?

# EOF
EOD
}

if [[ -e "$1" ]]; then
  error "FATAL: File exists: $1"
  exit 1
else
  if touch "$1"; then
    chmod +x "$1" || error "WARNING: Failed to add executable bit."

    boilerplate >> "$1" || exit 1
  else
    error "FATAL: Failed to create the file."
  fi
fi

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
