#!/usr/bin/env bash
#
error() {
  echo "$1" >&2 || return 1
}

usage() {
  cat <<EOD
flog initializes a new bash script with vim modelines, shebang, and the like.

Usage: flog [OPTION] FILENAME

Options
  -?, --help                  print this help and exit
EOD
  exit 1
}

if [[ -z "$1" ]]; then
  error "FATAL: FILENAME argument not optional. Try 'flog --help' for usage information."
fi


boilerplate() {
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n\n' '#'
  printf '%s\n' 'set -o nounset     # expanding unset variables is fatal'
  printf '%s\n\n' 'shopt -s nullglob  # globs that match nothing expand to ""'

cat <<EOD
main() {
  :
}

if [[ "\${BASH_SOURCE[0]}" == "\${0}" ]]; then
  main "\$@"
fi

# EOF
EOD
}

if [[ -e "$1" ]]; then
  error "FATAL: File exists: $1"
  exit 1
else
  if touch "$1"; then
    chmod +x "$1" || error "WARNING: Failed to add executable bit."

    boilerplate >> "$1" || exit
  else
    error "FATAL: Failed to create the file."
  fi
fi

# EOF
