#!/usr/bin/env bash
#

source $HOME/.bash_styles

echo \'\"default0
echo "${italic}"\'\"italic0"$eitalic"
echo "${bold}"\'\"bold0"$default"
echo "${under}"\'\"under0"$eunder"
echo "${alt}"\'\"alt"${ealt}"

# EOF
