#!/usr/bin/env bash
#

source $HOME/.bash_styles

string="oO08 iIlL1 g9qCGQ ~-+=>\'\""
string="$(<~/bin/test.txt)"

clear
echo "$string ""default"
hr
echo "bold"
echo "${bold}""$string ""$default"
hr
echo "italic"
echo "${italic}""$string ""$default"
hr
echo "dim"
echo "${dim}""$string ""$default"

# EOF
