#!/usr/bin/env bash
#

source $HOME/.bash_styles

string="oO08 iIlL1 g9qCGQ ~-+=>\'\""
string="$(<~/bin/test.txt)"

clear
echo "$string "
echo ""
echo "bold"
echo "${bold}""$string ""$default"
echo ""
echo "italic"
echo "${italic}""$string ""$default"
echo ""
echo "bold italic"
echo "${bold}""${italic}""$string ""$default"
echo ""
echo "dim"
echo "${dim}""$string ""$default"

# EOF
