#!/usr/bin/bash
#
# renames all files underneath the PWD to replace unwanted characters such as:
#       whitespace
#       parentheses
#       underscores
#       semicolon
#       ampersand

#make sure extended globbing is on
shopt -s extglob;

#debug?

#for each file
while IFS= read -rd '' file_full_path; do

    [[ "$DEBUG" ]] && printf "Step -0: %s\n" "$file_full_path"
    filename="${file_full_path##*/}"                   # fill $filename from parsed $file_full_path

    filename="${filename//'!'/#}"                      # substitute '!' with '#'

    [[ "$DEBUG" ]] && printf "Step 1: %s\n" "$filename"
    filename="${filename//+( )/.}"                     # substitute ' ' with '.' in $filename

    [[ "$DEBUG" ]] && printf "Step 2: %s\n" "$filename"
    filename="${filename//.-./..}"                     # substitute '.-.' with '..' in $filename

    [[ "$DEBUG" ]] && printf "Step 3: %s\n" "$filename"
    filename="${filename//\(/_}"                       # substitute '(' with '_'

    [[ "$DEBUG" ]] && printf "Step 4: %s\n" "$filename"
    filename="${filename//\)/_}"                       # substitute ')' with '_'

    [[ "$DEBUG" ]] && printf "Step 5: %s\n" "$filename"
    filename="${filename//;/_}"                        # substitute ';' with '_'

    [[ "$DEBUG" ]] && printf "Step 6: %s\n" "$filename"
    filename="${filename//\[/_}"                        # substitute '[' with '_'

    [[ "$DEBUG" ]] && printf "Step 7: %s\n" "$filename"
    filename="${filename//\]/_}"                        # substitute '[' with '_'

    #printf "New name: %s\n" "$filename"

    mv -v -n "$file_full_path" "${file_full_path%/*}/$filename"

done < <(find . -depth \( -type d -o -type f \) \( -name "* *" -o -name "*_*" -o -name '*.-.*' -o -name "*;*" \) -print0);

find . -depth \( -type d -o -type f \) \( -name "* *" -o -name '*.-.*' \) -print0;
