#!/usr/bin/env bash
#
# lock the screen and also mute the sound outputs
# see also: `thaw`
#
set -x
amixer sset Master off
xset dpms force off
xset +dpms
if type -a swaylock &>/dev/null ; then
  swaylock || exit
else
  xlock || exit
fi

while pgrep i3lock &> /dev/null; do
  sleep 2s
done

thaw
