#!/usr/bin/env python
"""Take an address and return lat/long coordinates.

Uses OSM Nominatim API:
* https://nominatim.org/release-docs/develop/api/Overview/
"""
import argparse
import sys
import os
import json
from urllib.parse import quote
import webbrowser

import requests


def get_location_details(address: str) -> dict:
    """
    Fetch location details for the given address using the Nominatim API.

    Args:
    address (str): The address to look up.

    Returns:
    dict: A dictionary containing the location details.
    """
    base_url = "https://nominatim.openstreetmap.org/search"
    query = quote(address)
    response = requests.get(f"{base_url}?q={query}&format=json")
    response.raise_for_status()
    data = response.json()
    if data:
        return data[0]
    else:
        return {}


def browse(osm_id: str) -> None:
    base_url = "https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid={osm_id}"
    webbrowser.open(base_url.format(osm_id=osm_id))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-w", "--web", help="Open a map in the browser", action="store_true"
    )
    parser.add_argument("address", help="Address to geolocate")
    args = parser.parse_args()

    details = get_location_details(args.address)

    if os.getenv["DEBUG"]:
        print(json.dumps(details, indent=2), file=sys.stderr)

    print(f"{details['lat']}, {details['lon']}")
    if args.web:
        browse(details["osm_id"])
