#!/usr/bin/env python
"""Take an address and return lat/long coordinates.

Uses OSM Nominatim API:
* https://nominatim.org/release-docs/develop/api/Overview/
"""
import sys
import json
from urllib.parse import quote
import webbrowser

import requests


def get_location_details(address: str) -> dict:
    """
    Fetch location details for the given address using the Nominatim API.

    Args:
    address (str): The address to look up.

    Returns:
    dict: A dictionary containing the location details.
    """
    base_url = "https://nominatim.openstreetmap.org/search"
    query = quote(address)
    response = requests.get(f"{base_url}?q={query}&format=json")
    response.raise_for_status()
    data = response.json()
    if data:
        return data[0]
    else:
        return {}


def browse(osm_id: str) -> None:
    base_url = "https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid={osm_id}"
    webbrowser.open(base_url.format(osm_id))


if __name__ == "__main__":
    address = sys.argv[1]
    details = get_location_details(address)
    print(f"{details['lat']}, {details['lon']}")
