#!/usr/bin/env bash
# GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin17.7.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.


main() {
  git difftool -y "$1"~1 "$1"
}

main "$@"

# EOF
