#!/usr/bin/bash
#
# returns the active git branch and shows if dirty
#

parse_git_branch ()
{
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

parse_git_dirty ()
{
    [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo '*'
}

BRANCH="$(parse_git_branch)"
echo "$BRANCH"
