#!/usr/bin/bash
#
# print a colorized diff side-by-side in the terminal and send it to the specified pager
#

#if no arguments were passed figure out a better pager
if [ -n "$@" ]; then
    [[ $(type less 2> /dev/null) ]] && page="less"
    [[ $(type most 2> /dev/null) ]] && page="most"
    [[ $(type pager 2> /dev/null) ]] && page="pager"
fi

#use the best diff application available

[[ $(type diff 2> /dev/null) ]] && dif="diff"
[[ $(type colordiff 2> /dev/null) ]] && dif="colordiff"
[[ $(type cdiff 2> /dev/null) ]] && dif="cdiff"

"$dif" -y $2 $5 | "$page"