#!/usr/bin/env bash
#
# print a colorized diff side-by-side in the terminal and send it to the specified pager
#

#if no arguments were passed, figure out a better pager
#[[ $(type less 2> /dev/null) ]] && page="less"
#[[ $(type most 2> /dev/null) ]] && page="most"
#[[ $(type pager 2> /dev/null) ]] && page="pager"

#diff -y $2 $5 | pager

#vimdiff "$2" "$5"

git difftool -t vimdiff
