#!/usr/bin/env bash
#
# give me a simple read of git status
#
red=$(echo -e $(tput op)$(tput setaf 197))
yel=$(echo -e $(tput op)$(tput setaf 229))
grn=$(echo -e $(tput op)$(tput setaf 112))
blu=$(echo -e $(tput op)$(tput setaf 117))
bad=$(echo -e $(tput op)$(tput setaf 000)$(tput setab 130))

    # start with git status --porcelain plus any other arguments
git status --porcelain
