#!/usr/bin/env python3
#
"""
halp.py

Usage: halp cOmMaNdIdOnTkNoW

some utils have their own idea of whether it should be '--help' or '-h' or '-?'
or some random combination and I'm tired of guessing when I'm in the midst of
trying to figure something else out

also, I like to page the output if it's long, but some commands
print help text to stdout and others to stderr. who wants to type '&> | pager'
all the damn time? not me.
"""
import sys
import subprocess
import shutil

COMMAND = sys.argv[1]

TRIES = (
    f"{COMMAND} --help",
    f"{COMMAND} -?",
    f"{COMMAND} -h",
    f"{COMMAND} help",
    f"{COMMAND} -help",
    f"tldr {COMMAND}",
    f"info {COMMAND}",
)


def main() -> None:
    # hold up: does this thing even exist on the system?
    if not shutil.which(COMMAND):
        print(f"Command not found: {COMMAND}")
        return 1

    for command in TRIES:
        p = subprocess.run(command.split(" "), capture_output=True)
        try:
            p.check_returncode()
        except subprocess.CalledProcessError:
            continue
        else:
            output = p.stdout.decode() + p.stderr.decode()
            if len(output.strip()):
                print(f"+ {command}")
                print(output)
                return
            else:
                # some shell commands, e.g. `test`, don't take arguments.
                # therefore, if the output from a successful try is zero
                # length, we should keep going.
                continue


if __name__ == "__main__":
    sys.exit(main())

# EOF
