#!/usr/bin/env python3
#
import shutil

CHAR = '-'
CHAR = "━"


def main() -> None:
    cols = shutil.get_terminal_size().columns

    for _ in range(0, cols):
        print(CHAR, end="")


if __name__ == "__main__":
    main()

# vim: ft=python:
# EOF
