#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# hub wrapper that implements some pretty formatting not yet in hub cli

if [[ -s "$HOME"/.bash_styles ]] ; then
  # shellcheck disable=SC1090
  source "$HOME/.bash_styles"
else
  echo "FATAL: styles file not found: $HOME/.bash_styles" 1>&2
  exit 1
fi

_hub_colorizer()
{
  # shellcheck disable=SC2154
  sed -r \
    -e "s@<#bold#>@$bold@g" \
    -e "s@<#ul#>@$under@g" \
    -e "s@<#yellow#>@$yellow@g" \
    -e "s@<#red#>@$red@g" \
    -e "s@<#green#>@$green@g" \
    -e "s@<#blue#>@$blue@g" \
    -e "s@<#magenta#>@$magenta@g" \
    -e "s@<#cyan#>@$cyan@g" \
    -e "s@<#white#>@$white@g" \
    -e "s@<#dim#>@$dim@g" \
    -e "s@<#black#>@$black@g" \
    -e "s@<#reset#>@${reset}${eunder}${eitalic}@g"
}

main() {
  # summary format (with url)
  hub issue --format="<#reset#><#green#> %i<#reset#> %t %l <#blue#><%au><#reset#> <#white#><#dim#>%U %n<#reset#>" | _hub_colorizer || return $?
}

main "$@"
exit $?
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
