#!/usr/bin/env bash
#
# modulate image brightness, saturation, and hue

set -o nounset     # expanding unset variables is fatal
shopt -s nullglob  # globs that match nothing expand to ""


_bak() {
  filename="$1"
  mv "$filename" "$filename".bak
}


adjust() {
  filename="$1"
  hue="${2:-100}"
  brightness="${3:-100}"
  saturation="${4:-100}"

  target="${filename/.png/.new.png}"

  if [[ ! -w "$filename" ]] ; then
    echo "$filename not writable"
    return
  fi

  if _bak "$filename"; then
    if (set -x ; magick -modulate "$brightness","$saturation","$hue" "$filename" "$target" && rm "$filename"); then
      (set -x ; mv "$target" "$filename")
    fi
  fi
}

main() {
  for file in "$@"; do
    adjust "$file" || break
  done
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  adjust "$@"
fi

# EOF
