#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# renames the focused i3 container

set -eu -o pipefail

if ! command -v awk >/dev/null 2>&1 ; then echo "Missing dependency: awk" 1>&2 ; exit 1 ; fi
if ! command -v sed >/dev/null 2>&1 ; then echo "Missing dependency: sed" 1>&2 ; exit 1 ; fi
if ! command -v wmctrl >/dev/null 2>&1 ; then echo "Missing dependency: wmctrl" 1>&2 ; exit 1 ; fi
if ! command -v xdotool >/dev/null 2>&1 ; then echo "Missing dependency: xdotool" 1>&2 ; exit 1 ; fi
if ! command -v xprop >/dev/null 2>&1 ; then echo "Missing dependency: xprop" 1>&2 ; exit 1 ; fi

main() {
  focused=$(wmctrl -lp | grep "$(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/')")
  fpid=$(awk '{print $3}' <<< "$focused")
  fnme=$(cut -f -4  -d ' ' --complement <<< "$focused")
  xdotool search -all --pid "$fpid" --name "$fnme" set_window -name "$*"
}

main "$@"

# EOF
