#!/usr/bin/env python3
#
import urllib.request


def main():
    with urllib.request.urlopen(
        "https://evilinsult.com/generate_insult.php?lang=en"
    ) as r:
        print(r.read().decode())


if __name__ == "__main__":
    main()

# EOF
