#!/usr/bin/env bash
# GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin17.7.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# sends a file or data stream to the pastebin at ix.io using the netrc credentials

netrc="$HOME/.dotfiles/data/private/netrc"

if ! [[ -s "$netrc" ]] >/dev/null 2>&1 ; then echo "Missing netrc file: $netrc" 1>&2 ; exit 1 ; fi

curl -v --netrc-file "$netrc" --form 'f:1=<-' ix.io < "${1:-/proc/self/fd/0}"

# EOF
