#!/usr/bin/env bash
#
# sends a file or data stream to the pastebin at ix.io using the netrc credentials

netrc="$HOME/.dotfiles/data/private/netrc"

if ! [[ -s "$netrc" ]] >/dev/null 2>&1 ; then echo "Missing netrc file: $netrc" 1>&2 ; exit 1 ; fi

# ix.io
# curl --netrc-file "$netrc" --form 'f:1=<-' ix.io < "${1:-/proc/self/fd/0}"

# paste.rs now with https support
curl --netrc-file "$netrc" --data-binary @- https://paste.rs < "${1:-/dev/stdin}"

# EOF
