#!/usr/bin/env bash
#
# Prints a diff of two json arrays using jq

if ! command -v jq >/dev/null 2>&1 ; then echo "Missing dependency: jq" 1>&2 ; exit 1 ; fi

diff <(jq . -M -S < "$1") <(jq . -M -S < "$2")
