#!/usr/bin/env bash
#
# Prints a diff of two json arrays using jq

if ! command -v jq >/dev/null 2>&1 ; then echo "Missing dependency: jq" 1>&2 ; exit 1 ; fi

vimdiff <(jq . --sort-keys < "$1") <(jq . --sort-keys < "$2")
