#!/usr/bin/env bash
# GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2017 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
if ! type psx &> /dev/null; then echo "Missing dependency: psx" 1>&2; exit 1; fi

# Parameters {{{1
#
while :
do
  case $1 in
    --help | -\?)
      usage
      exit 0
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      verbose=$((verbose+1))
      shift
      ;;
    -9 | --kill)
      kill="1"
      shift
      ;;
    -q | --quiet)
      quiet="1"
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
# Parameters 1}}}

if [[ -n "$kill" ]]; then
  args="-9"
fi

while read -r line; do
  kill "$args" "$line"
done < <(psx "$1")

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
