#!/usr/bin/env bash
#

if ! type psx &> /dev/null; then echo "Missing dependency: psx" 1>&2; exit 1; fi

# Parameters {{{1
#
while :
do
  case $1 in
    --help | -\?)
      usage
      exit 0
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      verbose=$((verbose+1))
      shift
      ;;
    -9 | --kill)
      kill="1"
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
# Parameters 1}}}

if [[ -n "$kill" ]]; then
  args="-9"
fi

while read -r line; do
  if [[ -n "$args" ]]; then
    kill "$args" "$line"
  else
    kill "$line"
  fi
done < <(psx "$1")

# EOF
