#!/usr/bin/env bash
#
# takes a task definition family and saves all revisions of that family to separate json files
# in the cwd

set -o nounset

# Dependencies {{{1
needed_dependencies="awk jq aws"
missing_dependencies=""

is_missing=0
for dependency in $needed_dependencies; do
  if ! command -v "$dependency" > /dev/null 2>&1; then
    # If not found, add to missing_dependencies string
    missing_dependencies="$missing_dependencies $dependency"
    is_missing=1
  fi
done

if [ $is_missing -eq 1 ]; then
  printf "Required dependencies are missing:%s\n" "$missing_dependencies"
  exit 1
fi

unset needed_dependencies missing_dependencies is_missing
# Dependencies 1}}}

main() {
  family="$1"
  region="${2:-us-west-2}"

  # get all task definition versions for the given family
  task_definition_arns=$(aws ecs list-task-definitions --family-prefix "$family" --region "$region" | jq -r '.taskDefinitionArns[]')

  echo "Task definitions found:"
  echo "$task_definition_arns"
  for arn in $task_definition_arns; do
    # get the task definition version from the ARN
    version=$(echo "$arn" | awk -F/ '{print $NF}' | awk -F: '{print $2}')

    # download the task definition
    (set -x ; aws ecs describe-task-definition --task-definition "$arn" --region "$region" > "$family-v$version.json" ) || break
  done
}

main "$@"

# EOF
