#!/usr/bin/env python3
#
"""Pretty print JSON blobs.
Split long strings into lists of strings in JSON blobs and then pretty print.
"""

import sys
import json


def split_lines(mydict: dict) -> dict:
    for k, v in mydict.items():
        if isinstance(v, dict):
            mydict[k] = split_lines(v)
        elif isinstance(v, str):
            mydict[k] = v.split("\n") if len(v.split("\n")) > 1 else v

    return mydict


def main():
    data = '\n'.join(sys.stdin.readlines())
    jsondata = split_lines(json.loads(data))
    print(json.dumps(jsondata, indent=2, default=str))


if __name__ == "__main__":
    main()

# EOF
