#!/usr/bin/env python3
#
"""Displays a random cat pic in your browser."""
import json
import urllib.request
import webbrowser

__RANDOM_CAT__ = "https://aws.random.cat/meow"


def main():
    with urllib.request.urlopen(__RANDOM_CAT__) as r:
        img_url = json.loads(r.read().decode()).get("file")

    webbrowser.open(img_url)


if __name__ == "__main__":
    main()

# EOF
