#!/usr/bin/env bash
#
# mirror DISPLAY1 output to DISPLAY2

DIS1="DP-1"
DIS2="DP-2"

set -o nounset

trap process_sigint INT
trap die EXIT

die() {
  ( set -x ; \
    pkill wl-mirror
    swaymsg output "$DIS2" disable
  )
  exit
}

process_sigint() {
  echo "Control-C was pressed." 1>&2
  die
}

main() {
  ( set -x ; \
    swaymsg output "$DIS2" enable && \
    wl-mirror --fullscreen-output "$DIS2" "$DIS1"
  )
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi

# EOF
