#!/usr/bin/env bash
# GNU bash, version 4.3.18(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Applies some day time styles and plays a tone to tell me to get out of bed
# Invoking this with cron

# Functions {{{1
verbose() {
  if [[ "$verbose" -ge "1" ]] && [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}

error() {
  if [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}
# 1}}}

tmux_daystyle="/home/ryan/.config/tmux/color-cool.conf"
morning_tone="/media/vault/public/audio/effects/pdsounds/STE-003.mp3"

broadcast Good morning
if [[ -f "$tmux_daystyle" ]]; then
  tmux source-file "$tmux_daystyle" 1> /dev/null
else
  error "tmux day style not found."
fi

if [[ -f "$morning_tone" ]]; then
  play -q "$morning_tone" &
else
  error "morning tone not found."
fi

# vim: ft=sh foldmethod=marker:
