#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

main() {
  # from http://stackoverflow.com/a/8597411/1266551
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo "linux"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
          # Mac OSX
  elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo "cygwin"
      # POSIX compatibility layer and Linux environment emulation for Windows
  elif [[ "$OSTYPE" == "msys" ]]; then
    echo "msys"
      # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
  elif [[ "$OSTYPE" == "win32" ]]; then
    echo "mingw"
      # I'm not sure this can happen.
  elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo "bsd"
  else
    return 1
  fi
  return 0
}

main "$@" || exit 1
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
