#!/usr/bin/env bash
#

case "$OSTYPE" in
  "linux"*)
    echo "linux" ;;
  "darwin"*)
    echo "macos" ;;
  "cygwin")
    echo "cygwin" ;;
  "msys")
    # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
    echo "msys" ;;
  "win32")
    # I'm not sure this can happen.
    echo "mingw" ;;
  "freebsd"*)
    echo "bsd" ;;
  *)
    echo "unknown" ;
    return 1 ;;
esac

# EOF
