#!/usr/bin/env bash
#
# return the number of outdated packages
#

#Make sure pacman exists
if ! type pacman &> /dev/null; then echo "Missing dependency: pacman" 1>&2; exit 1; fi

#Store a count of out of date packages
count="$(pacman -Qu | wc -l)"

#Return the count
echo "$count"

#If outdated packages were found, exit with an error code. Otherwise, don't.
if [[ "$count" -ne 0 ]]; then
  exit 1
else
  exit 0
fi
