#!/usr/bin/env sh
#
# read standard input into my preferred pager settings
#

if command -v ifne 2> /dev/null 1>&2 ; then
  ifne less -r -X -F < "${1:-/dev/fd/0}"
else
  echo "WARNING: ifne not found. The pager may misbehave if stdin is empty. Install moreutils." 1>&2
  exec less -r -X -F < "${1:-/dev/fd/0}"
fi
