#!/usr/bin/env sh
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

less -R -X < "${1:-/proc/self/fd/0}"

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
