#!/usr/bin/env python3
#
"""
Read input and upload it to a secure pastebin.
Then copy the resulting link to the clipboard.
"""
import requests
import pyperclip
import fileinput


def main():
    url = "https://paste.rs"
    data = "".join(line for line in fileinput.input())

    response = requests.post(url, data=data)
    content = response.content

    # Copy the response to the clipboard
    pyperclip.copy(content.decode())

    # Ensure the response has a trailing newline
    print(f"copied to clipboard: '{content.decode()}'")


if __name__ == "__main__":
    main()
