#!/usr/bin/env bash
#

ostype="$(ostype)"

if [[ "$ostype" == "linux" ]] ; then
  # kitty +kitten clipboard < /dev/stdin
  xclip -in -selection clipboard
elif [[ "$ostype" == macos ]] ; then
  /usr/bin/pbcopy < /dev/stdin
else
  exit 1
fi

# EOF
