#!/usr/bin/env bash
#
# add standard input to the system clipboard
#

if ! command -v ostype >/dev/null 2>&1 ; then
  echo "Missing dependency: ostype" 1>&2
  exit 1
else
  ostype="$(ostype)"
fi

if [[ "$ostype" == "linux" ]] ; then
  if command -v wl-copy >/dev/null 2>&1 ; then
    wl-copy
  else
    xclip -in -selection clipboard
  fi
elif [[ "$ostype" == macos ]] ; then
  /usr/bin/pbcopy < /dev/stdin
else
  exit 1
fi

# EOF
