#!/usr/bin/env bash
#
# paste the system clipboard to standard output
#

if ! command -v ostype >/dev/null 2>&1 ; then
  echo "Missing dependency: ostype" 1>&2
  exit 1
else
  ostype="$(ostype)"
fi

if [[ "$ostype" == "linux" ]] ; then
  if command -v wl-paste >/dev/null 2>&1 ; then
    wl-paste
  else
    xclip -out -selection clipboard
  fi
elif [[ "$ostype" == macos ]] ; then
  /usr/bin/pbpaste
else
  exit 1
fi

# EOF
