#!/usr/bin/env python3
#
from datetime import timedelta
import subprocess
import sys
import time


class HumanInterval:
    """Will have to finish this later."""

    def __init__(self, ms):
        self.ms = ms
        self.delta = timedelta(milliseconds=ms)

    @property
    def human(self):
        result = ""
        if self.delta.days > 365:
            result + f"{self.delta.days // 365} years, "


if __name__ == "__main__":
    arg = " ".join(sys.argv[1:])

    start_t = time.time()
    proc = subprocess.run(sys.argv[1:])  # noqa: S603
    ms = round(1000 * (time.time() - start_t), 2)
    duration = timedelta(milliseconds=ms)

    run_args = " ".join(proc.args)
    print(f"command executed was {run_args}")
    print(f"duration was {duration}")
