#!/usr/bin/env python3
#
import sys
import time
import subprocess


if __name__ == "__main__":
    arg = " ".join(sys.argv[1:])

    start_t = time.time()
    proc = subprocess.run(sys.argv[1:])  # noqa: S603
    duration = round(1000 * (time.time() - start_t), 2)

    run_args = " ".join(proc.args)
    print(f"command executed was {run_args}")
    print(f"duration was {duration} ms")
