#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
if [[ -r ~/.bash_styles ]]; then source ~/.bash_styles; fi

# Functions {{{1
log() {
  local msg=$1
  local level="${2:-INFO}"
  now=$(date "+%Y-%m-%d %H:%M:%S%z")
  echo "$now ${default}${cyan}$(hostname) ${magenta}$(basename "$0")${default}:$level $msg" 1>&2
}
# Functions 1}}}

main() {
  version="${1-3}"
  if [[ "$version" -ne 2 ]] && [[ "$version" -ne 3 ]] ; then
    log "Version must be 2 or 3: $version"
    exit 1
  fi

  while read -r app; do
    log "Upgrading $app"
    awk -F= '{print "pip'"$version"' install -U "$1}' <<< "$app" | { sh || exit 1 ;}
  done < <(pip"$version" freeze --local --no-color)
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
