#!/usr/bin/env python3
#
import subprocess
from typing import Dict, List

_PIPX_APPS: Dict[str, List[str | None]] = {
    "black": [],
    "daff": [],
    "downforeveryone": [],
    "dumbpw": [],
    "em-keyboard": [],
    "extinfo": [],
    "flake8": [
        "flake8-bandit",
        "flake8-bugbear",
        "flake8-simplify",
        "flake8-pie",
    ],
    "gallery-dl": [
        "yt-dlp",
    ],
    "howdoi": [],
    "mdformat": [
        "mdformat-toc",
        "mdformat-gfm",
        "mdformat-black",
        "mdformat-frontmatter",
    ],
    "mypy": [],
    "pre-commit": [],
    "ptpython": [],
    "pudb": [],
    "pwstore": [],
    "pyupgrade": [],
    "rich-cli": [],
    "thefuck": [],
    "tldr": [],
    "twine": [],
    "uncolor": [],
    "yamllint": [],
    "yt-dlp": [],
}

_XONTRIBS = [
    "ptpython",
    "prompt_toolkit",
    "xonsh-direnv",
    "xontrib-argcomplete",
    "xontrib-avox-poetry",
    "xontrib-commands",
    "xontrib-gruvbox",
    "xontrib-jedi",
    "xontrib-kitty",
]


def _cmd(command: str, check: bool = True) -> None:
    print(f"+ {command}")
    subprocess.run(command.split(), check=check)


def main() -> None:
    for pipx_app in _PIPX_APPS.keys():
        break
        _cmd(f"pipx uninstall --verbose {pipx_app}", check=False)
        _cmd(f"pipx install --verbose {pipx_app}")
        for inject in _PIPX_APPS[pipx_app]:
            _cmd(f"pipx inject --verbose {pipx_app} {inject}")

    for xontrib in _XONTRIBS:
        _cmd(f"pip install --isolated --user {xontrib}", check=True)


if __name__ == "__main__":
    main()

# EOF
