#!/usr/bin/env python3
#
import subprocess
from typing import Dict, List

_PIPX_APPS: Dict[str, List[str | None]] = {
    "black": [],
    "daff": [],
    "downforeveryone": [],
    "dumbpw": [],
    "em-keyboard": [],
    "extinfo": [],
    "flake8": [
        "flake8-bandit",
        "flake8-bugbear",
        "flake8-simplify",
        "flake8-pie",
    ],
    "gallery-dl": [
        "yt-dlp",
    ],
    "howdoi": [],
    "mdformat": [
        "mdformat-toc",
        "mdformat-gfm",
        "mdformat-black",
        "mdformat-frontmatter",
    ],
    "mypy": [],
    "pre-commit": [],
    "ptpython": [],
    "pudb": [],
    "pwstore": [],
    "pyupgrade": [],
    "rich-cli": [],
    "thefuck": [],
    "tldr": [],
    "twine": [],
    "uncolor": [],
    "xonsh": [
        "ptpython",
        "prompt_toolkit",
        "xonsh-direnv",
        "xontrib-argcomplete",
        "xontrib-avox-poetry",
        "xontrib-commands",
        "xontrib-gruvbox",
        "xontrib-jedi",
        "xontrib-kitty",
    ],
    "yamllint": [],
    "yt-dlp": [],
}

def _cmd(command: str, check: bool = True) -> None:
    print(f"+ {command}")
    subprocess.run(command.split(), check=check)

def main() -> None:
    for pipx_app in _PIPX_APPS.keys():
        _cmd(f"pipx reinstall {pipx_app}")
        for inject in _PIPX_APPS[pipx_app]:
            _cmd(f"pipx inject {pipx_app} {inject}")



if __name__ == "__main__":
    main()

# EOF
