#!/usr/bin/env python3
#
import subprocess
from typing import Dict, List, Union

T_AppsList = Dict[str, List[Union[str, None]]]

_PIPX_APPS: T_AppsList = {
    "black": [],
    "daff": [],
    "downforeveryone": [],
    "dumbpw": [],
    "em-keyboard": [],
    "extinfo": [],
    "flake8": [
        "flake8-bandit",
        "flake8-bugbear",
        "flake8-simplify",
        "flake8-pie",
    ],
    "gallery-dl": [
        "yt-dlp",
    ],
    "howdoi": [],
    "mdformat": [
        "mdformat-toc",
        "mdformat-gfm",
        "mdformat-black",
        "mdformat-frontmatter",
    ],
    "mypy": [],
    "pre-commit": [],
    "ptpython": [],
    "pudb": [],
    "pwstore": [],
    "pyupgrade": [],
    "rich-cli": [],
    "thefuck": [],
    "tldr": [],
    "twine": [],
    "uncolor": [],
    "xonsh": [
        "prompt_toolkit",
        "ptpython",
        "xonsh-direnv",
        "xontrib-abbrevs",
        "xontrib-argcomplete",
        "xontrib-avox-poetry",
        "xontrib-commands",
        "xontrib-gruvbox",
        "xontrib-jedi",
        "xontrib-kitty",
        "xontrib-vox",
        "xontrib-whole-word-jumping",
    ],
    "yamllint": [],
    "yt-dlp": [],
}

_PIP_APPS: T_AppsList = {
    "requests": [],
    "pyperclip": [],
}


def _cmd(command: str, check: bool = True) -> None:
    print(f"+ {command}")
    subprocess.run(command.split(), check=check)


def main() -> None:
    for pip_app in _PIP_APPS.keys():
        _cmd(
            "pip3 --no-input --disable-pip-version-check --isolated "
            f"install --compile --upgrade --user {pip_app}"
        )

    for pipx_app in _PIPX_APPS.keys():
        _cmd(f"pipx reinstall {pipx_app}")
        for inject in _PIPX_APPS[pipx_app]:
            _cmd(f"pipx inject {pipx_app} {inject}")


if __name__ == "__main__":
    main()

# EOF
