#!/usr/bin/env bash
#
# create a playlist in mpv with arbitrary paths as inputs and play it with
# some arguments I usually need
#

trap 'trapexit $? $LINENO' EXIT

if ! command -v _playlist >/dev/null 2>&1 ; then echo "Missing dependency: _playlist" 1>&2 ; exit 1 ; fi
if ! command -v mpv >/dev/null 2>&1 ; then echo "Missing dependency: mpv" 1>&2 ; exit 1 ; fi

trapexit() {
  rm -f "$tmpfile"
}

main() {
  local targets=("$@")
  tmpfile="$(mktemp --suffix=mpv)"
  chmod 0600 "$tmpfile" || return

  for target in "${targets[@]}"; do
    if [[ -r "$target" ]] ; then # it's a file
      printf "%s\n" "$(realpath "$target")" >> "$tmpfile"
    else # maybe it's a directory?
      printf "%s\n" "$target" >> "$tmpfile"
    fi
  done

  if [[ ! -s "$tmpfile" ]]; then
    echo "No readable targets were found: ${targets[*]}" 1>&2
    return 1
  fi

  exec _playlist "$tmpfile"
}

main "$@"
