#!/usr/bin/env bash
#
# create a playlist in mpv with arbitrary paths as inputs and play it with
# some arguments I usually need
#

trap 'trapexit $? $LINENO' EXIT

trapexit() {
  (set -x ; rm -f "$tmpfile")
}

main() {
  local targets=("$@")
  tmpfile="$(mktemp --suffix=mpv)"
  chmod 0600 "$tmpfile" || return

  for target in "${targets[@]}"; do
    if [[ -r "$target" ]] ; then # it's a file
      printf "%s\n" "$(realpath "$target")" >> "$tmpfile"
    else
      printf "%s\n" "$target" >> "$tmpfile"
    fi
  done

  ( set -x ; mpv --loop-playlist --volume=50 --shuffle --playlist="$tmpfile" )
}

main "$@"
