#!/usr/bin/env bash
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Usage {{{1
#
usage() {
cat <<EOD
pyflog initializes a new python script with vim modelines, shebang, and the like.

Usage: pyflog [OPTION] FILENAME

Options
  -?, --help                  print this help and exit
EOD
exit 1
}
# 1}}}
# Validation {{{1
if [[ -z "$1" ]]; then
  error "FATAL: Argument not optional. Try 'pyflog --help' for usage information."
fi
# 1}}}

boilerplate() {
  copyright="$(copyright || return)"
  printf '%s\n' '#!/usr/bin/env python3'
  printf '%s\n' '# vim: ft=python expandtab smarttab shiftwidth=4 softtabstop=4'
  printf '%s\n' '#'
  printf '__author__ = "%s (%s)"\n' "${COPYRIGHT_HOLDER:-Ryan Delaney}" "${GIT_AUTHOR_EMAIL:-ryan.delaney@gmail.com}"
  printf '__date__ = "%s"\n' "$(date +'%Y-%m-%d')"
  printf '__copyright__ = """%s\n' "$copyright"
  printf '%s\n' "$(disclaimer)"
  printf '%s\n' '"""'
cat <<EOD


def main():
    pass


if __name__ == "__main__":
    main()

# EOF
EOD
}

if [[ -e "$1" ]]; then
  error "FATAL: File exists: $1"
  exit 1
else
  if touch "$1"; then
    chmod +x "$1" || error "WARNING: Failed to add executable bit."

    boilerplate >> "$1" || exit
  else
    error "FATAL: Failed to create the file."
    exit 1
  fi
fi

# EOF
