#!/usr/bin/env bash
#

# Usage {{{1
#
usage() {
cat <<EOD
pyflog initializes a new python script with vim modelines, shebang, and the like.

Usage: pyflog [OPTION] FILENAME

Options
  -?, --help                  print this help and exit
EOD
exit 1
}
# 1}}}
# Validation {{{1
if [[ -z "$1" ]]; then
  error "FATAL: Argument not optional. Try 'pyflog --help' for usage information."
fi
# 1}}}

boilerplate() {
  printf '%s\n' '#!/usr/bin/env python3'
  printf '%s\n' '#'
cat <<EOD


def main() -> None:
    pass


if __name__ == "__main__":
    main()

# EOF
EOD
}

if [[ -e "$1" ]]; then
  error "FATAL: File exists: $1"
  exit 1
else
  if touch "$1"; then
    chmod +x "$1" || error "WARNING: Failed to add executable bit."

    boilerplate >> "$1" || exit
  else
    error "FATAL: Failed to create the file."
    exit 1
  fi
fi

# EOF
