#!/usr/bin/env bash
#
# run speaker-test with some less horrifically
# defeaning output than you get with the defaults
#

main() {
  (set -x ; \
    timeout 3 \
    /usr/bin/speaker-test \
    --scale 20 \
    --test=pink \
    --nloops 3 \
    "$@"
  )
}

main "$@"

# EOF
