#!/usr/bin/env bash
#
# Reads STDIN and splits the input according to delimiters passed in $@
#

read -r line

main() {
  IFS="${*:- }" read -r -a array <<< "$line"

  for element in "${array[@]}"
  do
    echo "$element"
  done
}

main "$@"

# EOF
