#!/usr/bin/env bash
# GNU bash, version 4.4.19(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# Reads STDIN and splits the input according to delimiters passed in $@

read -r line

main() {
  IFS="$@" read -r -a array <<< "$line"

  for element in "${array[@]}"
  do
    echo "$element"
  done
}

main "$@"
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
