#!/usr/bin/env bash
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# returns true if the count of identities in the current ssh-agent is non-zero
#
# TODO: use -q switch for quiet output: returns true if identified, false for
# all others
# Usage {{{1
#
usage() {
cat <<EOD
sshauthed
© Copyright 2014 Ryan Delaney. All rights reserved.
Web site: http://github.com/rpdelaney

sshauthed returns true if the count of identities in the current ssh-agent is
non-zero, and returns false if zero or ssh-agent was not found

Usage: sshauthed [OPTION]

Options
  -?, --help                  print this help and exit
  -v, --verbose               print the number of identities to standard output
  -q, --quiet                 suppress all output (default behavior, over-rides -v)
EOD
exit 1
}
# 1}}}
# Functions {{{1
verbose() {
  if [[ "$verbose" -ge "1" ]] && [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}

error() {
  if [[ -z "$quiet" ]]; then
    echo "$1" >&2 || return 1
  fi
}
# 1}}}
# Parameters {{{1
#
while :
do
  case $1 in
    --help | -\?)
      usage
      exit 0
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      verbose=$((verbose+1))
      shift
      ;;
    -q | --quiet)
      quiet="1"
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
# 1}}}
# Validation {{{1
if ! type mktemp &> /dev/null; then echo "ERROR: Missing dependency: mktemp" 1>&2; exit 1; fi
if ! type ssh-add &> /dev/null; then echo "ERROR: Missing dependency: ssh-add" 1>&2; exit 1; fi
# 1}}}
# Main {{{1
# Create a temporary file and store the path
tmpfile="$(mktemp)"

if [[ -f "$tmpfile" ]]; then
  ssh-add -L &> "$tmpfile"
else
  exit 1
fi

result="$(<"$tmpfile")"

case "$result" in
    "Could not open a connection to your authentication agent.")
        verbose "0"
        rm "$tmpfile"
        exit 1
        ;;
    "The agent has no identities.")
        verbose "0"
        rm "$tmpfile"
        exit 1
        ;;
    *)
        verbose "$(wc -l < "$tmpfile")"
        rm "$tmpfile"
        exit 0
        ;;
esac
# 1}}}

# vim: ft=sh foldmethod=marker:
