#!/usr/bin/env bash
# GNU bash, version 4.3.18(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# shell script to produce my statusbar mesage way better than i3bar
#
#

# Business {{{1
config="/home/ryan/.config/i3status/i3status.conf"

i3status -c "$config" | while read line; do
    echo "$line" || exit 1
done
# }}}
