#!/usr/bin/env bash
# GNU bash, version 4.3.18(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# shell script to produce my statusbar mesage way better than i3bar
#
#
# Functions {{{1
verbose() {
  if [[ "$verbose" = "1" ]]; then
    echo "$1" >&2
  fi
}

error() {
  echo "$1" >&2
}
# }}}
# Usage {{{1
#
usage() {
cat <<EOD
statusbar
© Copyright 2014 Ryan Delaney. All rights reserved.
Web site: http://github.com/rpdelaney

statusbar prints out a status bar just how I like it.

Usage: statusbar [OPTION]

Options
  -?, --help                  print this help and exit
  -v, --verbose               increase verbosity
EOD
exit 1
}
# }}}
# Main {{{1
while sleep 2; do
  date="$(date --iso-8601=minutes)"

  if [[ "$database" ]]; then
    db=""
  fi

  echo "$db$date" || exit 1
done
# }}}


# vim: ft=sh foldmethod=marker:
