#!/usr/bin/env python3
#
# print a random strategy. for when you don't know what to do!
#
import os
import random


def main() -> None:
    with open(f"{os.getenv('HOME')}/bin/strategy.txt") as f:
        strategies = list(f)

    print(random.choice(strategies), end="")


if __name__ == "__main__":
    main()

# EOF
