#!/usr/bin/env bash
#
# take the clipboard contents and replace with a summary using gptalk
# if the contents were a url, keep the url in the result

# Dependencies {{{1
dependencies="gptalk isurl notice pbpaste pbcopy"
missing_dependencies=""

is_missing=0
for dependency in $dependencies; do
  if ! command -v "$dependency" > /dev/null 2>&1; then
    # If not found, add to missing_dependencies string
    missing_dependencies="$missing_dependencies $dependency"
    is_missing=1
  fi
done

if [ $is_missing -eq 1 ]; then
  printf "Required dependencies are missing:%s\n" "$missing_dependencies"
  exit 1
fi

unset dependencies missing_dependencies is_missing
# Dependencies 1}}}

main() {
  data="$(pbpaste)"
  summary="$(set -x ; echo "$data" | gptalk tldr)" || exit
  notice "tldr'ing some stuff, don't touch your clipboard"

  if isurl "$data"; then
    ( echo "$data" && echo "$summary" ) | pbcopy || exit
    notice "tldr'd a url"
  else
    echo "$summary" | pbcopy || exit
    notice "tldr'd some content"
  fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi

# EOF
