#!/usr/bin/env bash
#
# share a file via transfer.sh

set -u

main() {
  filename="$1"
  basename="$(basename "$filename")" || return

  if [[ -r "$filename" ]]; then
    if ! pv "$filename" | curl -Ss --upload-file - https://transfer.sh/"$basename" ; then
      pv "$filename" | curl -F"file=@$filename" https://0x0.st
    fi
  fi
}

main "$@"

# EOF
