#!/usr/bin/env bash
#
# share a file via transfer.sh

set -u
if ! command -v pv >/dev/null 2>&1 ; then echo "Missing dependency: pv" 1>&2 ; exit 1 ; fi
if ! command -v curl >/dev/null 2>&1 ; then echo "Missing dependency: curl" 1>&2 ; exit 1 ; fi

main() {
  filename="$1"
  basename="$(basename "$filename")" || return

  if [[ -r "$filename" ]]; then
    if ! ( set -x ; pv "$filename" | curl -Ss --upload-file - https://transfer.sh/"$basename" ); then
      ( set -x ; pv "$filename" | curl -F"file=@$filename" https://0x0.st )
    fi
  fi
}

main "$@"

# EOF
