#!/usr/bin/env bash
#
# rotate a video
# https://stackoverflow.com/questions/3937387/rotating-videos-with-ffmpeg

set -o nounset -o pipefail

if ! command -v ffmpeg >/dev/null 2>&1 ; then echo "Missing dependency: ffmpeg" 1>&2 ; exit 1 ; fi
if ! command -v bak >/dev/null 2>&1 ; then echo "Missing dependency: bak" 1>&2 ; exit 1 ; fi

mode="$2"

mv "$1" "$1".bak

# "soft" transposition using metadata
# the player must support it, but most do anymore
( set -x ; ffmpeg -display_rotation "$mode" -i "$1".bak -codec copy "$1" )

touch --reference="$1".bak "$1"
