#!/usr/bin/env python3
#
import subprocess
import os
import sys

OP_OBJECTS = {
    "trussworks-id": "u65jqpgpxva2fh5gkv4prtcgda",  # rpdelaney@trussworks-id
}


def main():
    if (AWS_PROFILE := os.environ.get("AWS_PROFILE")) and (
        AWS_ID_PROFILE := os.environ.get("AWS_ID_PROFILE")
    ):
        # Use the 1password CLI to get the MFA token
        command = ["op", "item", "get", OP_OBJECTS[AWS_ID_PROFILE], "--otp"]
        print(f'+ {" ".join(command)}')
        mfa_secret = subprocess.check_output(command).decode().strip()

        # Use the MFA token to login to AWS using aws-vault
        command = ["aws-vault", "login", AWS_PROFILE]
        print(f'+ echo {mfa_secret} | {" ".join(command)}')
        process = subprocess.Popen(command, stdin=subprocess.PIPE)
        process.communicate(input=mfa_secret.encode())
    else:
        print("Error: environment variable is not set.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
