#!/usr/bin/env bash
#
# 1 create a snapshot of current plugins in /tmp/
# 2 upgrade vim-plug itself
# 3 clean the vim-plug directory (remove plugins not in the vimrc)
# 4 update the remaining plugins
# 5 install any missing plugins

declare threads=3

if vim -c 'PlugSnapshot! /tmp/vim-plug-'"$(date +'%s')" -c 'bd!' -c 'PlugUpgrade' -c 'PlugClean!' -c 'PlugUpdate '"$threads" -c 'PlugInstall '"$threads" -c 'qa!' ; then
  echo "vim plugins upgraded 💫"
fi

# EOF
