#!/usr/bin/env bash
# GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin17.7.0)
# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
#
# © Copyright 2019 Ryan Delaney. All rights reserved.
#
# 1 create a snapshot of current plugins in /tmp/
# 2 upgrade vim-plug itself
# 3 clean the vim-plug directory (remove plugins not in the vimrc)
# 4 update the remaining plugins
# 5 install any missing plugins

declare threads=3

main() {
  vim -c 'PlugSnapshot! /tmp/vim-plug-'"$(date +'%s')" -c 'bd!' -c 'PlugUpgrade' -c 'PlugClean!' -c 'PlugUpdate '"$threads" -c 'PlugInstall '"$threads" -c 'qa!'
}

main "$@"

# EOF
