#!/usr/bin/bash
#
# Perform an internet search from the command line
#
googurl="http://www.google.com/search?q="
ddgourl="http://duckduckgo.com/?q="

query="$@"
AGENT="Mozilla/4.0"
stream=$(curl -A "$AGENT" -skLm 10 "${googurl}\"${Q/\ /+}\"" | grep -oP '\/url\?q=.+?&amp' | sed 's/\/url?q=//;s/&amp//')
echo -e "${stream//\%/\x}"
