#!/usr/bin/bash
#
#where the heck am I?
#
namei "$PWD" -x -m | \
sed -r 's@f\:\s(.*)@'$bold$red'\1'$reset'@' | \
sed -r 's@^\s(\s*)D@'$bold$yellow'\1Mn'$reset'@' | \
sed -r 's@^\s(\s*)l@'$bold$cyan'\1Ln'$reset'@'
