#!/usr/bin/env bash
#
#where the heck am I?
#

styles="$HOME/.bash_styles"
if [[ -f "$styles" ]]; then source ~/.bash_styles; fi

namei "$PWD" -x -m | \
sed -r 's@f\:\s(.*)@'"$bold$green"'\1'$reset'@' | \
sed -r 's@^\s(\s*)D@'"$bold$yellow"'\1Mn'$reset'@' | \
sed -r 's@^\s(\s*)l@'"$bold$cyan"'\1Ln'$reset'@'
