#!/usr/bin/env bash
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

error() {
  echo "$1" >&2
}

if [[ -d "/media/apps/wine32" ]]; then
  prefix="/media/apps/wine32"
else
  error "Prefix directory not found: $prefix"
  exit 1
fi

export WINEPREFIX="$prefix"
export WINEARCH=win32

if [[ -n "$*" ]]; then
  wine "$@"
fi

# EOF
