#!/usr/bin/env bash
#
# helper to load a specific wineprefix I have optimized for 32-bit applications
#

error() {
  echo "$1" >&2
}

if [[ -d "/media/apps/wine32" ]]; then
  prefix="/media/apps/wine32"
else
  error "Prefix directory not found: $prefix"
  exit 1
fi

export WINEPREFIX="$prefix"
export WINEARCH=win32

if [[ -n "$*" ]]; then
  wine "$@"
fi

# EOF
