#!/usr/bin/env bash
#
# lock the screen on xorg the way I like to lock the screen (using i3wm and i3lock)
#

if ! command -v i3lock > /dev/null 2>&1 ; then echo "Missing dependency: i3lock" 1>&2 ; exit 1 ; fi

i3lock --ignore-empty-password \
  --show-failed-attempts \
  --pointer=win \
  --color=3f3f3f \
  --beep \
# --no-unlock-indicator
