#!/usr/bin/env bash
# GNU bash, version 4.3.33(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2015 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# :command! yt -js  { dactyl.execute(';yt'); dactyl.execute('command2'); }

# Trap the first line of the output from youtube-dl -g
read video < <(youtube-dl -g "$1")

#\mplayer -loop 0 -fixed-vo -softvol -msgcolor -fs -quiet "$video"
mpv "$video"

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
