#!/usr/bin/env bash
# GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
#
# © Copyright 2018 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
if ! command -v youtube-dl &> /dev/null; then echo "Missing dependency: youtube-dl" 1>&2; exit 1; fi
if ! command -v yt-id &> /dev/null; then echo "Missing dependency: yt-id" 1>&2; exit 1; fi
if ! command -v mplayer &> /dev/null; then echo "Missing dependency: mplayer" 1>&2; exit 1; fi
if ! command -v convert &> /dev/null; then echo "Missing dependency: convert" 1>&2; exit 1; fi

# Create an animated gif from a Youtube video
url="$1"
id="$(yt-id "$url")"
# this should use mktemp
[[ -n "$TMPDIR" ]] || { echo "FATAL: TMPDIR env var must be set." 1>&2 ; exit 1 ;}
tmpfile="$TMPDIR/$id.flv"

set -e -o pipefail
youtube-dl -o "$tmpfile" "$url"
mplayer "$tmpfile" -ss 03:16 -endpos 5 -vo jpeg:outdir="$id":quality=100:smooth=30:progressive -vf scale=320:240 -nosound
convert -delay 4 -loop 0 "$TMPDIR/$id"/*.jpg "$TMPDIR/$id".gif

# vim: filetype=sh foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
